In [5]:
import pandas as pd
import numpy as np

#load the employment data for each employment excel file
employment_data = pd.read_excel('employment_data/allhlcn20.xlsx')
employment_data2 = pd.read_excel('employment_data/allhlcn201.xlsx')
employment_data3 = pd.read_excel('employment_data/allhlcn202.xlsx')
employment_data4 = pd.read_excel('employment_data/allhlcn203.xlsx')
employment_data5 = pd.read_excel('employment_data/allhlcn204.xlsx')

# reading the first few lines of each employment data file to understand the data structure
print(employment_data.head())
print(employment_data2.head())
print(employment_data3.head())
print(employment_data4.head())
print(employment_data5.head())

  Area\nCode  St  Cnty  Own  NAICS  Year Qtr Area Type St Name        Area  \
0      US000  US   0.0    0     10  2020   A    Nation     NaN  U.S. TOTAL
1      US000  US   0.0    1     10  2020   A    Nation     NaN  U.S. TOTAL
2      US000  US   0.0    2     10  2020   A    Nation     NaN  U.S. TOTAL
3      US000  US   0.0    3     10  2020   A    Nation     NaN  U.S. TOTAL
4      US000  US   0.0    5     10  2020   A    Nation     NaN  U.S. TOTAL

            Ownership                  Industry Annual Average Status Code  \
0       Total Covered  10 Total, all industries                        NaN
1  Federal Government  10 Total, all industries                        NaN
2    State Government  10 Total, all industries                        NaN
3    Local Government  10 Total, all industries                        NaN
4             Private  10 Total, all industries                        NaN

   Annual Average Establishment Count  Annual Average Employment  \
0                            10487687                  139103773
1                               61310                    2928036
2                               70059                    4592925
3                              171044                   13642800
4                            10185275                  117940012

   Annual Total Wages  Annual Average Weekly Wage  Annual Average Pay  \
0       8905606771748                        1231               64021
1        250251253418                        1644               85467
2        302037717914                        1265               65762
3        776054840247                        1094               56884
4       7577262960169                        1236               64247

   Employment Location Quotient Relative to U.S.  \
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

   Total Wage Location Quotient Relative to U.S.
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0
  Area\nCode  St  Cnty  Own  NAICS  Year  Qtr Area Type St Name        Area  \
0      US000  US   0.0    0     10  2020    1    Nation     NaN  U.S. TOTAL
1      US000  US   0.0    1     10  2020    1    Nation     NaN  U.S. TOTAL
2      US000  US   0.0    2     10  2020    1    Nation     NaN  U.S. TOTAL
3      US000  US   0.0    3     10  2020    1    Nation     NaN  U.S. TOTAL
4      US000  US   0.0    5     10  2020    1    Nation     NaN  U.S. TOTAL

   ...                  Industry Status Code Establishment Count  \
0  ...  10 Total, all industries         NaN            10355102
1  ...  10 Total, all industries         NaN               61260
2  ...  10 Total, all industries         NaN               69971
3  ...  10 Total, all industries         NaN              170991
4  ...  10 Total, all industries         NaN            10052880

   January Employment  February Employment  March Employment  \
0           147231429            147811747         147065115
1             2837972              2839762           2859018
2             4634306              4707994           4714212
3            14522123             14660818          14691308
4           125237028            125603173         124800577

   Total Quarterly Wages  Average Weekly Wage  \
0          2339427644605                 1221
1            56654217644                 1532
2            74578427472                 1224
3           195973897954                 1031
4          2012221101535                 1236

   Employment Location Quotient Relative to U.S.  \
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

   Total Wage Location Quotient Relative to U.S.
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

[5 rows x 21 columns]
  Area\nCode  St  Cnty  Own  NAICS  Year  Qtr Area Type St Name        Area  \
0      US000  US   0.0    0     10  2020    2    Nation     NaN  U.S. TOTAL
1      US000  US   0.0    1     10  2020    2    Nation     NaN  U.S. TOTAL
2      US000  US   0.0    2     10  2020    2    Nation     NaN  U.S. TOTAL
3      US000  US   0.0    3     10  2020    2    Nation     NaN  U.S. TOTAL
4      US000  US   0.0    5     10  2020    2    Nation     NaN  U.S. TOTAL

   ...                  Industry Status Code Establishment Count  \
0  ...  10 Total, all industries         NaN            10383036
1  ...  10 Total, all industries         NaN               61259
2  ...  10 Total, all industries         NaN               70023
3  ...  10 Total, all industries         NaN              170970
4  ...  10 Total, all industries         NaN            10080784

   April Employment  May Employment  June Employment  Total Quarterly Wages  \
0         127242130       130712810        135045869          2023546517413
1           2864177         2869572          2883816            64676714199
2           4647567         4599140          4493711            74524271719
3          13918360        13594230         13268287           199218388051
4         105812026       109649868        114400055          1685127143444

   Average Weekly Wage  Employment Location Quotient Relative to U.S.  \
0                 1188                                            1.0
1                 1732                                            1.0
2                 1252                                            1.0
3                 1127                                            1.0
4                 1179                                            1.0

   Total Wage Location Quotient Relative to U.S.
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

[5 rows x 21 columns]
  Area\nCode  St  Cnty  Own  NAICS  Year  Qtr Area Type St Name        Area  \
0      US000  US   0.0    0     10  2020    3    Nation     NaN  U.S. TOTAL
1      US000  US   0.0    1     10  2020    3    Nation     NaN  U.S. TOTAL
2      US000  US   0.0    2     10  2020    3    Nation     NaN  U.S. TOTAL
3      US000  US   0.0    3     10  2020    3    Nation     NaN  U.S. TOTAL
4      US000  US   0.0    5     10  2020    3    Nation     NaN  U.S. TOTAL

   ...                  Industry Status Code Establishment Count  \
0  ...  10 Total, all industries         NaN            10515058
1  ...  10 Total, all industries         NaN               61375
2  ...  10 Total, all industries         NaN               70121
3  ...  10 Total, all industries         NaN              171108
4  ...  10 Total, all industries         NaN            10212454

   July Employment  August Employment  September Employment  \
0        135086021          137112322             138722896
1          2912631            3161849               3122492
2          4473976            4495108               4576801
3         11638075           12375685              13586320
4        116061339          117079680             117437283

   Total Quarterly Wages  Average Weekly Wage  \
0          2086885772754                 1172
1            59960225613                 1505
2            75462200946                 1286
3           175304577462                 1076
4          1776158768733                 1169

   Employment Location Quotient Relative to U.S.  \
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

   Total Wage Location Quotient Relative to U.S.
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

[5 rows x 21 columns]
  Area\nCode  St  Cnty  Own  NAICS  Year  Qtr Area Type St Name        Area  \
0      US000  US   0.0    0     10  2020    4    Nation     NaN  U.S. TOTAL
1      US000  US   0.0    1     10  2020    4    Nation     NaN  U.S. TOTAL
2      US000  US   0.0    2     10  2020    4    Nation     NaN  U.S. TOTAL
3      US000  US   0.0    3     10  2020    4    Nation     NaN  U.S. TOTAL
4      US000  US   0.0    5     10  2020    4    Nation     NaN  U.S. TOTAL

   ...                  Industry Status Code Establishment Count  \
0  ...  10 Total, all industries         NaN            10697552
1  ...  10 Total, all industries         NaN               61344
2  ...  10 Total, all industries         NaN               70121
3  ...  10 Total, all industries         NaN              171105
4  ...  10 Total, all industries         NaN            10394982

   October Employment  November Employment  December Employment  \
0           140824498            141390186            141000256
1             2979117              2897791              2908240
2             4598026              4594771              4579493
3            13794712             13885183             13778496
4           119452643            120012441            119734027

   Total Quarterly Wages  Average Weekly Wage  \
0          2455746836976                 1339
1            68960095962                 1811
2            77472817777                 1298
3           205557976780                 1144
4          2103755946457                 1352

   Employment Location Quotient Relative to U.S.  \
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

   Total Wage Location Quotient Relative to U.S.
0                                            1.0
1                                            1.0
2                                            1.0
3                                            1.0
4                                            1.0

[5 rows x 21 columns]

In [13]:
#select the specific columns relevant to the COIVD-19 data as a whole using the original employment_data
selected_columns = ['Area', 'Annual Average Employment', 'Annual Average Pay']
employment_selected_data =  employment_data[selected_columns]

#display the updated excel file to only include Area, Annual Average Employment, and Annual Average Pay
print(employment_selected_data.head())

         Area  Annual Average Employment  Annual Average Pay
0  U.S. TOTAL                  139103773               64021
1  U.S. TOTAL                    2928036               85467
2  U.S. TOTAL                    4592925               65762
3  U.S. TOTAL                   13642800               56884
4  U.S. TOTAL                  117940012               64247